SET NAMES 'utf8mb4';

CREATE TABLE IF NOT EXISTS supported_languages(
  id INT PRIMARY KEY AUTO_INCREMENT,
  abbreviation VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL
);

-- INSERT INTO supported_languages (abbreviation, name) VALUES ("EN", "English");

CREATE TABLE IF NOT EXISTS users(
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) UNIQUE NOT NULL,
  language_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dictionary_languages(
  id INT PRIMARY KEY AUTO_INCREMENT,
  abbreviation VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS dictionaries(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  main_language_id INT NOT NULL,
  secondary_language_id INT NOT NULL,
  is_shared BIT(1) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS labels(
  id INT PRIMARY KEY AUTO_INCREMENT,
  dictionary_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  colour VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS labels_to_words(
  id INT PRIMARY KEY AUTO_INCREMENT,
  label_id INT NOT NULL,
  word_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chapters(
  id INT PRIMARY KEY AUTO_INCREMENT,
  dictionary_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  given_number INT,
  given_letter VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chapters_to_words(
  id INT PRIMARY KEY AUTO_INCREMENT,
  label_id INT NOT NULL,
  word_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS words(
  id INT PRIMARY KEY AUTO_INCREMENT,
  dictionary_id INT NOT NULL,
  main_language_val VARCHAR(255) NOT NULL,
  secondary_languageval VARCHAR(255) NOT NULL,
  voice VARCHAR(255) NOT NULL,
  given_date DATETIME NOT NULL,
  is_learned BIT(1) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exams(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  mode ENUM('MAIN_HIDDEN', 'SECONDARY_HIDDEN', 'MATCHING') NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exams_to_words(
  id INT PRIMARY KEY AUTO_INCREMENT,
  exam_id INT NOT NULL,
  word_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
